### ISSUE TITLE
bad link hiking and cycling

### ISSUE THREAD

**Issue by Louis-LJ** [mariush444/Osmand-tools#1]
Good morning,

you pointed out osmand renderings from my personal github directory but they are not maintained.

https://github.com/Louis-LJ/OsmAnd_Cycling_Map/blob/main/README_EN.md
and 
https://github.com/Louis-LJ/OsmAnd_Hiking_Map/blob/main/README-EN.md
is old 

now they are kept up to date in this directory:
https://github.com/OsmAnd-Rendering

**Comment by mariush444** [comment]
Thank you for info.
I will change the links.
Have a good day.
