### ISSUE TITLE
Additional items for OsmAnd users (Italian documentation and a couple of map styles)

### ISSUE THREAD

**Issue by Max1234-Ita** [mariush444/Osmand-tools#2]
Hi, I found your repo very interesting; I have one too,  https://github.com/Max1234-Ita/GuidaOsmand, where I have put some stuff I made for OsmAnd.

If you like, please feel free to add it to your list :-)

Main items hosted there are:

- _Guida non Ufficiale a OsmAnd_ ("Unofficial Guide to OsmAnd"): several pdf files containing a beginner's guide to OsmAnd and some mini-tutorial explaining how to report bugs, reinstall OsmAnd, translate the User Interface, etc. (in Italian only, so far). I made them in my spare time as an integration to the official docs, for Italian, non-English speakers; English version will come -maybe- in the future);

- _Highlighted Admin Boundaries_ and _Highlighted Admin Borders v.2_, 2 map styles I derived from the Default style for myself and to help a friend who's currently traveling around the World. If interested, please link this item in your list: https://github.com/Max1234-Ita/GuidaOsmand/blob/main/risorse/rendering/en_highlighted_boundaries.md

Thanks for your attention (and have a happy navigation :-)
Max

**Comment by mariush444** [comment]
Done. Thank you and have a good day :)
